apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "2"
  creationTimestamp: "2025-10-09T13:21:58Z"
  generation: 1
  name: fastapi-db
  namespace: fastapi
  resourceVersion: "147563"
  uid: 099cbb79-5c86-46be-b8bd-7fa5ed128df1
spec:
  affinity:
    podAntiAffinityType: preferred
  bootstrap:
    initdb:
      database: fastapi
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: ariu
      secret:
        name: app-secret
  enablePDB: true
  enableSuperuserAccess: false
  failoverDelay: 0
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 1
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: false
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      full_page_writes: "on"
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_worker_processes: "32"
      shared_memory_type: mmap
      shared_preload_libraries: ""
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_keep_size: 512MB
      wal_level: logical
      wal_log_hints: "on"
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  probes:
    liveness:
      isolationCheck:
        connectionTimeout: 1000
        enabled: true
        requestTimeout: 1000
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  resources: {}
  smartShutdownTimeout: 180
  startDelay: 3600
  stopDelay: 1800
  storage:
    resizeInUseVolumes: true
    size: 1Gi
  switchoverDelay: 3600
status:
  availableArchitectures:
  - goArch: amd64
    hash: 433bae32a2e3e459a2a181d67ed2b0dfcf67f359480b9646bbdc8ad8e2dd4ef1
  - goArch: arm64
    hash: 981f8452ecf423a37802c14018b7a73bfd25c1c2e82ec19de9c85cd54912adb7
  certificates:
    clientCASecret: fastapi-db-ca
    expirations:
      fastapi-db-ca: 2026-01-07 13:16:58 +0000 UTC
      fastapi-db-replication: 2026-01-07 13:16:58 +0000 UTC
      fastapi-db-server: 2026-01-07 13:16:58 +0000 UTC
    replicationTLSSecret: fastapi-db-replication
    serverAltDNSNames:
    - fastapi-db-rw
    - fastapi-db-rw.fastapi
    - fastapi-db-rw.fastapi.svc
    - fastapi-db-rw.fastapi.svc.cluster.local
    - fastapi-db-r
    - fastapi-db-r.fastapi
    - fastapi-db-r.fastapi.svc
    - fastapi-db-r.fastapi.svc.cluster.local
    - fastapi-db-ro
    - fastapi-db-ro.fastapi
    - fastapi-db-ro.fastapi.svc
    - fastapi-db-ro.fastapi.svc.cluster.local
    serverCASecret: fastapi-db-ca
    serverTLSSecret: fastapi-db-server
  cloudNativePGCommitHash: 8b442dcc3
  cloudNativePGOperatorHash: 981f8452ecf423a37802c14018b7a73bfd25c1c2e82ec19de9c85cd54912adb7
  conditions:
  - lastTransitionTime: "2025-10-10T09:24:53Z"
    message: A single, unique system ID was found across reporting instances.
    reason: Unique
    status: "True"
    type: ConsistentSystemID
  - lastTransitionTime: "2025-10-10T09:24:53Z"
    message: Cluster is Ready
    reason: ClusterIsReady
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-10-09T13:22:04Z"
    message: Continuous archiving is working
    reason: ContinuousArchivingSuccess
    status: "True"
    type: ContinuousArchiving
  configMapResourceVersion:
    metrics:
      cnpg-default-monitoring: "12078"
  currentPrimary: fastapi-db-1
  currentPrimaryTimestamp: "2025-10-09T13:22:03.967034Z"
  healthyPVC:
  - fastapi-db-1
  image: ghcr.io/cloudnative-pg/postgresql:17.5
  instanceNames:
  - fastapi-db-1
  instances: 1
  instancesReportedState:
    fastapi-db-1:
      ip: 10.244.0.7
      isPrimary: true
      timeLineID: 1
  instancesStatus:
    healthy:
    - fastapi-db-1
  latestGeneratedNode: 1
  managedRolesStatus: {}
  pgDataImageInfo:
    image: ghcr.io/cloudnative-pg/postgresql:17.5
    majorVersion: 17
  phase: Cluster in healthy state
  poolerIntegrations:
    pgBouncerIntegration: {}
  pvcCount: 1
  readService: fastapi-db-r
  readyInstances: 1
  secretsResourceVersion:
    applicationSecretVersion: "12031"
    clientCaSecretVersion: "12039"
    replicationSecretVersion: "12043"
    serverCaSecretVersion: "12039"
    serverSecretVersion: "12041"
  switchReplicaClusterStatus: {}
  systemID: "7559211673623957527"
  targetPrimary: fastapi-db-1
  targetPrimaryTimestamp: "2025-10-09T13:21:58.827499Z"
  timelineID: 1
  topology:
    instances:
      fastapi-db-1: {}
    nodesUsed: 1
    successfullyExtracted: true
  writeService: fastapi-db-rw
